---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle

inputs:
- name: pipelines
- name: app-source
- name: version

outputs:
- name: build

run:
  path: pipelines/gradle/tasks/build.sh
